language: python
python:
 - 3.6
install:
 - sudo apt-get install unixodbc-dev
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest pytest-cov
script:
 - pytest --cov=./ 
after_success:
  - codecov
